volumes:
  db-data:
  redis-data:

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    restart: always
    env_file:
      - .env
    build:
      context: app
      dockerfile: Dockerfile
      args:
        env: ${ENV}
    ports:
      - "8000:8000"
#    command: gunicorn --config ./gunicorn_config.py src.main:app
    command: uvicorn src.main:app --port 8000 --host 0.0.0.0
    depends_on:
      - db
      - celery
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app/:/code

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  celery:
    restart: always
    build: app
    command: celery --app=src.celery_tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
